Models/BestRestaurantContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Models
{
  public class BestRestaurantsContext : DbContext
  {
    public DbSet<Cuisine> Cuisines { get; set; }
    public DbSet<Restaurant> Restaurants { get; set; }

    public BestRestaurantsContext(DbContextOptions options) : base(options) { }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Cuisine
  {
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>();
    }

    public int CuisineId { get; set; }
    public string CuisineName { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; }
  }
}

Controllers/CuisinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public CuisinesController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      List<Restaurant> restaurants = _db.Restaurants.Where(restaurant => restaurant.CuisineId == id).ToList();
      ViewData.Add("cuisine", thisCuisine);
      ViewData.Add("restaurants", restaurants);
      return View();
    }

    public ActionResult Edit(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      var restaurants = _db.Restaurants.Where(restaurant => restaurant.CuisineId == id);
      foreach (Restaurant restaurant in restaurants)
      {
        _db.Restaurants.Remove(restaurant);
      }      
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurants.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BestRestaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public RestaurantsController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurant => restaurant.Cuisine).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "CuisineName");
      return View();
    }

    [HttpPost]
    public ActionResult Create (Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "CuisineName");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit (Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}
@using BestRestaurants.Models;
@model BestRestaurants.Models.Cuisine

<h1>Add a new cuisine</h1>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.CuisineName)
  @Html.TextBoxFor(model => model.CuisineName)
  <input type="submit" value="Add a new cuisine" />
}

<p>@Html.ActionLink("Show all cuisines", "Index")</p>

Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}
@using BestRestaurants.Models;
@model BestRestaurants.Models.Cuisine;

<h1>Delete a Cuisine</h1>
<p>Are you sure you'd like to delete this cuisine?</p>
<hr />
<h3>@Html.DisplayFor(model => model.CuisineName) </h3>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete">
}

<p>@Html.ActionLink("Show all cuisines", "Index")</p>

Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models

@{
  Cuisine cuisine = ViewData["cuisine"] as Cuisine;
  List<Restaurant> restaurants = ViewData["restaurants"] as List<Restaurant>;
}

<h2>Cuisine Details</h2>
<hr />

<h3>Cuisine Name: @cuisine.CuisineName</h3>
<ul>
@foreach (Restaurant restaurant in restaurants)
{
  <li>@Html.ActionLink(restaurant.Name, "Details", "Restaurants", new { id = restaurant.RestaurantId})</li>
}
</ul>
<p>@Html.ActionLink("Edit Cuisine", "Edit", new { id = cuisine.CuisineId })</p>
<p>@Html.ActionLink("Delete Cuisine", "Delete", new { id = cuisine.CuisineId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h2>Edit</h2>

<h4>Edit this cuisine: @Html.DisplayFor(model => model.CuisineName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId);

  @Html.LabelFor(model => model.CuisineName)
  @Html.EditorFor(model => model.CuisineName)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;

<h1>Cuisines</h1>

@if (@Model.Count == 0)
{
  <h2>There is nothing to see here!</h2> 
}

@foreach (Cuisine cuisine in Model)
{
  <li>@Html.ActionLink($"{cuisine.CuisineName}", "Details", new {id = cuisine.CuisineId})</li>
}

<p>@Html.ActionLink("Add a new cuisine", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Hi, These are the Best Restaurants in the World!</h1>
<p>@Html.ActionLink("See all restaurants", "Index", "Restaurants")</p>
<p>@Html.ActionLink("See all cuisines", "Index", "Cuisines")</p>

Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h3>Edit Restaurants</h3>

<h4>Edit this!: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)
  @Html.LabelFor(model => model.Location)
  @Html.EditorFor(model => model.Location)
  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")

  <input type = "submit" value = "Save" />

}

<p>@Html.ActionLink("Back to List", "Index")</p>

Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Restaurant>;

<h1>Restaurants</h1>

@if (@Model.Count == 0)
{
  <h2>There is nothing to see here!</h2> 
}

@foreach (Restaurant restaurant in Model)
{
  <li>@Html.ActionLink($"{restaurant.Name}", "Details", new {id = restaurant.RestaurantId}) | @restaurant.Cuisine.CuisineName</li>
}

<p>@Html.ActionLink("Add a new restaurant", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Best Restaurants in the World</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="~/css/styles.css">
</head>
<body>
  @RenderBody()
</body>
</html>